### ISSUE TITLE
I have reserved reddit.com/r/r3stack

### ISSUE THREAD

**Issue by morningrat** [r3stack/r3stack#3]
Want it? I don't have anything to do with it.

**Comment by Bartekus** [comment]
We certainly would use it, as we would a spokesperson if that's something that would interest you!?
After all, we are group of passionated individuals and we are always open to anybody that in some way, shape or form also share that passion with us.
To me it's a bit of a sign that we are heading in the right direction since the people behind this stack have gathered under the flag of organization (araphel.org) that was created to honor and carry on the social justice legacy that Aaron Swartz, who as you might know, was after all one of the grandfathers of reddit! Indeed, I do not believe in coincidences and I strongly believe what Aaron said one... I think that something we all can understand and above all, appreciate and live by:

"With enough of us, around the world, we’ll not just send a strong message opposing the privatization of knowledge — we’ll make it a thing of the past. Will you join us?"
- Aaron_Swartz

**Comment by petermikitsh** [comment]
A gitter might not be a bad idea. The push notifications can be nice feature. People with questions can get faster responses.

**Comment by Bartekus** [comment]
@petermikitsh As per your suggestion, a gitter channel has been created and is open for business!

**Comment by Bartekus** [comment]
@morningrat I haven't heard from you and I'm not sure what you've decided to do but for now I'm going to close this issue. However please free to reopen me or contact me directly at bartekus~AT~gmail~DOT~com
