### ISSUE TITLE
Cannot find module 'babel-register'

### ISSUE THREAD

**Issue by veenified** [r3stack/r3stack#6]
Hi all, I have been playing with "meatier" and I happened open this stack when browsing the issues log and I was excited that there is an effort to build a more serious, stable, and production ready stack based on the work @mattkrick did.

I am having trouble just getting the boilerplate up and running though...
I have tried running `azk start` and `azk start -vv && azk logs --follow` and `azk start --rebuild` but I continue to get an error reporting that 'babel-register' module can't be found when 'server.babel.js' is run... even after running `npm install`. Attached is the verbose output ([verbose.txt](https://github.com/r3stack/r3stack/files/153551/verbose.txt)).

Any help would be much appreciated.

**Comment by Bartekus** [comment]
To keep a log and to help people should they find themselves facing similar problem, this issue was caused by introduction of this code into the azkfile.js:
```
other: {
    extends: "r3stack",
    envs: {
      NODE_ENV: "production",
    },
  },
```
At the moment, the build is not yet fully optimized and as such when attempting to use this setting, devDependencies will not be present in the build and in their absence, the app will fail to start.
In near future we will attempt to reconcile this problem by moving the appropriate devDependencies modules into dependencies which in turn will allow the higher mentioned setting to work, along with more concise overall optimization.
